INSERT INTO GAME_ROLE (ID, NAME ,PROF) VALUES (1, '薇恩','射手');
INSERT INTO GAME_ROLE (ID, NAME,PROF) VALUES (2, '乐芙兰','法师');
INSERT INTO GAME_ROLE (ID, NAME,PROF) VALUES (3, '盲僧','战士');
INSERT INTO GAME_ROLE (ID, NAME,PROF) VALUES (4, '墨菲特','坦克');